#!/bin/sh

HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$HOOK_DIR/lib.sh"

echo "Running Ruff ..."

enqueue_sound  "$RUFF_SOUND"

BEFORE=$(git diff --name-only)

cd "$REPO_ROOT"

# Type

mypy .

mypy_status=$?

if [ $mypy_status -ne 0 ]; then
    echo "Commit blocked: Type Errors to fix"
    enqueue_sound  "$(pick_random_no_sound)"
    exit 1
fi

# Linter

ruff check . --fix

if [ $ruff_status -ne 0 ]; then
    echo "Committ blocked: Ruff linted ... Please re-stage changes and commit again"
    enqueue_sound  "$(pick_random_failure_sound)"
    exit 1
fi

# Format

black .

if [ $black_status -ne 0 ]; then
    echo "Commit blocked: Black formatted to format the code"
    enqueue_sound  "$(pick_random_failure_sound)"
    exit 1
fi

# Double Check

AFTER=$(git diff --name-only)

if [ "$BEFORE" != "$AFTER" ]; then
    echo "Commit blocked: Please fix any errors, re-stage changes and commit again"
    enqueue_sound  "$(pick_random_no_sound)"
    exit 1
fi

enqueue_sound  "$REPO_ROOT/.githooks/sounds/success/charm.wav"