#!/bin/sh

HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$HOOK_DIR/lib.sh"

echo "Running Ruff ..."

enqueue_sound  "$RUFF_SOUND"

BEFORE=$(git diff --name-only)

# Linter and Format
cd "$REPO_ROOT"
ruff check . --fix

black .

AFTER=$(git diff --name-only)

if [ "$BEFORE" != "$AFTER" ]; then
    echo "⚠️ Ruff modified files"
    echo "Please re-stage changes and commit again"
    enqueue_sound  "$(pick_random_no_sound)"
    exit 1
fi

enqueue_sound  "$REPO_ROOT/.githooks/sounds/success/charm.wav"