#!/bin/sh

# Load in files
HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$HOOK_DIR/lib.sh"



cd "$REPO_ROOT"

# Type

mypy . 

mypy_status=$?

if [ $mypy_status -ne 0 ]; then
    echo "Push blocked: Type Errors to fix"
    enqueue_sound  "$(pick_random_failure_sound)"
    exit 1
fi

# Linter
echo "Running Ruff ..."
enqueue_sound  "$RUFF_SOUND"
ruff check .

ruff_status=$?

if [ $ruff_status -ne 0 ]; then
    echo "Push blocked: Ruff lint errors detected"
    enqueue_sound  "$(pick_random_failure_sound)"
    exit 1
fi

# Format
black --check .

black_status=$?

if [ $black_status -ne 0 ]; then
    echo "Push blocked: Black failed to format the code"
    enqueue_sound  "$(pick_random_failure_sound)"
    exit 1
fi

# Double Check

if ! git diff --quiet; then
    echo "Push blocked: formatting issues detected"
    enqueue_sound  "$(pick_random_failure_sound)"
    exit 1
fi

# Tests
TEST_COVERAGE=1


pytest --cov=. --cov-fail-under=$TEST_COVERAGE || {
    echo "Tests failed or coverage too low"
    enqueue_sound "$(pick_random_failure_sound)"
    exit 1
}

enqueue_sound  "$(pick_random_success_sound)"
