#!/bin/sh

HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$HOOK_DIR/lib.sh"

echo "Running Ruff ..."

play_sound "$RUFF_SOUND"

# Linter
ruff check . --fix

# Format
ruff format . 

if ! git diff --quiet; then
    echo "⚠️ Ruff modified files"
    echo "Please re-stage changes and commit again"

    exit 1
fi