[project]
name = "messedupfarm"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "arcade==3.3.3",
    "black>=26.5.1",
    "fastapi>=0.141.1",
    "requests>=2.34.2",
    "types-requests>=2.33.0.20260712",
    "uvicorn>=0.52.3",
    "websockets>=17.0.1",
]

[tool.ruff]
line-length = 88
target-version = "py311"
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist"
]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "SIM"]
# E = PEP8/style issues
# F = pyflakes bugs (unused/undefined code)
# I = import sorting
# B = bug-risk patterns
# UP = modern Python syntax upgrades
# SIM = simplification/refactoring suggestions
ignore = ["E501"] # Line too long

# TODO add S and ~W to our pyproject.toml
# Issue URL: https://github.com/Messed-Up-Farm-Studios/MessedUpFarm/issues/22

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"] # Allow assert in tests

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["server", "shared", "client"]

[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
/(venv|\.venv|\.git|__pycache__|build|dist)/
'''

[dependency-groups]
dev = [
    "black>=26.5.1",
    "mypy>=2.3.0",
    "pyinstaller>=6.21.0",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]
