name: Code Quality

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  mypy-ruff-black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install mypy ruff black
        run: pip install mypy ruff black
        
      - name: mypy
        run: mypy . 

      - name: Lint
        run: ruff check .

      - name: Install Black
        run: pip install black

      - name: Format
        run: black --check .
    