name: Lint

on:
  push:
  pull_request:

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install ruff
        run: pip install ruff
      
      - name: Lint
        run: ruff check .

      - name: Format
        run: ruff format . --check
    